spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/schedule
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        default_batch_fetch_size: 50